"""añadir cambios sintaxis variables

Revision ID: 15e82ac73ca2
Revises: 4b0d9890edeb
Create Date: 2023-09-14 12:34:17.894534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e82ac73ca2'
down_revision = '4b0d9890edeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price', sa.String(length=40), nullable=True))
        batch_op.drop_constraint('unique_stripePrice', type_='unique')
        batch_op.create_unique_constraint('uq_stripe_price', ['stripe_price'])
        batch_op.drop_column('stripePrice')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))
        batch_op.drop_column('userId')
        batch_op.drop_column('postalCode')
        batch_op.drop_column('fullName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullName', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('postalCode', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('full_name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripePrice', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('unique_stripePrice', ['stripePrice'])
        batch_op.drop_column('stripe_price')

    # ### end Alembic commands ###
