"""Migración inicial

Revision ID: 3da78049e8e8
Revises: 
Create Date: 2023-09-13 20:46:29.352895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da78049e8e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('order')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripePrice', sa.String(length=40), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_unique_constraint('unique_stripePrice', ['stripePrice'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=4, scale=2),
               existing_nullable=True)
        batch_op.drop_column('stripePrice')

    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fullName', sa.VARCHAR(length=100), nullable=False),
    sa.Column('orderStatus', sa.VARCHAR(length=60), nullable=True),
    sa.Column('orderTime', sa.DATETIME(), nullable=True),
    sa.Column('postalCode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantities', sa.TEXT(), nullable=False),
    sa.Column('totalAmount', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
