"""Añadir columna prices en order

Revision ID: c4e0c051ed37
Revises: 91e39f11e8ae
Create Date: 2023-09-14 15:21:26.049031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0c051ed37'
down_revision = '91e39f11e8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
